nelmio_cors:
    defaults:
        allow_origin: [ 'http://localhost:80' ]   # Origen de tu frontend
        allow_credentials: true
        allow_headers: [ 'Content-Type', 'Authorization' ]
        allow_methods: [ 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS' ]
        max_age: 3600
    paths:
        '^/':  # Aplica a todas las rutas
            allow_origin: [ 'http://localhost:80' ]
            allow_headers: [ 'Content-Type', 'Authorization' ]
            allow_methods: [ 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS' ]
            allow_credentials: true
