nelmio_cors:
    defaults:
        allow_origin: [ '*' ]           # Permite cualquier origen (desarrollo)
        allow_credentials: true
        allow_headers: [ 'Content-Type', 'Authorization' ]
        allow_methods: [ 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS' ]
        max_age: 3600
    paths:
        "^/login":
            allow_origin: [ "*" ]
            allow_headers: [ "*" ]
            allow_methods: ["POST", "OPTIONS"]
            allow_credentials: true
